---
title: "scrapDataSSP"
author: "Marcelo Avila"
date: "26 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(rvest)
library(stringr)
library(rebus)
library(lubridate)
library(RSelenium)
library(XML)
```

## Iniciar RSeleniun 

```{r message=FALSE, warning=FALSE}
rD <- rsDriver(port = 4567L, browser = "firefox")
remDr <- rD[["client"]]
```

### Funções reutilizáveis para o loop

```{r}
clickOccAno <- function() {
    webElemOcc <- remDr$findElement(using = 'css selector', "#conteudo_btnAnual")
    webElemOcc$clickElement()
}

clickRegTodos <- function() {
    cssRegTodos <- "#conteudo_ddlRegioes > option:nth-child(1)"
    webElemReg <- remDr$findElement(using = 'css selector', cssRegTodos)
    webElemReg$clickElement()
}
```


### declare some """globals"""
```{r}
g <- list()
g$dataPath <- "/data/electionBrazil/"
g$dataCleanPath <- paste0(g$dataPath, "SPCitiesClean/")
```


### Iniciar loop

```{r, eval = FALSE, echo=T, results='hide'}
# Chagen `eval = FALSE` to true

## abriar a página
urlSSP <- "http://www.ssp.sp.gov.br/Estatistica/Pesquisa.aspx"
remDr$navigate(urlSSP)
## Clicar ocorrencias registradas por ano
clickOccAno()

## click regiao: todos
clickRegTodos()

i <- 300
n <- 320
vector = i:n
for (i in vector) {
    
    ## STARTING
    cat(paste("Start: "))
    
    ## check ocorrencias registradas por ano
    
    ## check regiao 
    cssRegTodos <- "#conteudo_ddlRegioes"
    webElemReg <- remDr$findElement(using = 'css selector', cssRegTodos)
    opts <- webElemReg$selectTag()
    # if the first is not selected, click regiao todos
    if (!opts$selected[1]) { clickRegTodos() }
    
    
    ## select town 
    cssSel <- paste0("#conteudo_ddlMunicipios > option:nth-child(", i, ")")
    webElem <- remDr$findElement(using = 'css selector', cssSel)
    citystring <- webElem$getElementText()[[1]][1]
    
    cat("  :")
    
    ## Check if already downloaded
    listOfFiles <- list.files(g$dataCleanPath)
    citycheck <- paste0("clean_", citystring, ".csv")
    if (any(str_detect(listOfFiles, citycheck))) {  
        cat(paste(citystring, "already there!  :-)\n"))
        next
    }
    
    cat("-0  ")
    
    webElem$clickElement()
    cat(paste("Downloading", citystring))
    
    ## get table
    cat(" ...")
    cssTab <- paste0("#conteudo_gridAnual")
    webTab <- remDr$findElement(using = 'css selector', cssTab)
    tabcont <- webTab$getElementText()[[1]][1]
    listResult <- as.list(setNames(tabcont, citystring))
    
    
    # !
    cat("...")
    
    doc <- remDr$getPageSource()
    tab <-XML::readHTMLTable(doc[[1]],
                             header = T,
                             colClasses = "integer")[[1]]
    
    ## save data
    cat("...")
    
    filepathWrite <- paste0(g$dataCleanPath)
    write.csv2(x = tab,
               file = paste(filepathWrite,
                            paste0("clean_", citystring, ".csv"),
                            sep = "/"))
    
    ## done
    cat("   d:D\n")
}
```



trash
========================

```{r}
read.delim(text = listResult[[1]], sep = " ")
```

### click on first city

```{r}
# conteuno anual 
```
```{r}
#regiao: todos
cssRegTodos <- "#conteudo_ddlRegioes > option:nth-child(1)"
webElemReg <- remDr$findElement(using = 'css selector', cssRegTodos)
webElemReg$clickElement()
i = 3
cssSel <- paste0("#conteudo_ddlMunicipios > option:nth-child(", i, ")")
webElem <- remDr$findElement(using = 'css selector', cssSel)
webElem$getElementText()
```
